<?php

use Illuminate\Database\Seeder;

class StoresTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stores')->delete();

        DB::table('stores')->insert([
            ['id'=>'2389','store_country'=>'PT','store_name'=>'Aeroporto Lisboa AIRSIDE','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'2392','store_country'=>'PT','store_name'=>'Algarve Planta Alta ','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'2414','store_country'=>'ES','store_name'=>'ECI La Vaguada','store_area'=>'Madrid ','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'2420','store_country'=>'ES','store_name'=>'Oasis','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'2421','store_country'=>'ES','store_name'=>'Habaneras ','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS'],
            ['id'=>'2422','store_country'=>'ES','store_name'=>'Espai Girona','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate'],
            ['id'=>'2423','store_country'=>'ES','store_name'=>'Las Terrazas','store_area'=>'Canarias','store_segment'=>'Outlet','store_concept'=>'Intermediate'],
            ['id'=>'2428','store_country'=>'ES','store_name'=>'Aqua','store_area'=>'Levante ','store_segment'=>'Silver','store_concept'=>'Intermediate '],
            ['id'=>'2430','store_country'=>'ES','store_name'=>'Vialia','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'Intermediate'],
            ['id'=>'2431','store_country'=>'ES','store_name'=>"L'Aljub",'store_area'=>'Levante','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'2435','store_country'=>'ES','store_name'=>'Fañabe','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate'],
            ['id'=>'2439','store_country'=>'ES','store_name'=>'Area Sur ','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'2442','store_country'=>'ES','store_name'=>'Portal de la Marina','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2443','store_country'=>'ES','store_name'=>'El Campanario','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Basic'],
            ['id'=>'2451','store_country'=>'ES','store_name'=>'Getafe','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'2452','store_country'=>'ES','store_name'=>'Outletuy','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'2454','store_country'=>'ES','store_name'=>'Puerto Banús','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'2455','store_country'=>'ES','store_name'=>'La Cañada','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'2461','store_country'=>'ES','store_name'=>'Plaza del Duque','store_area'=>'Canarias','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'2462','store_country'=>'ES','store_name'=>'Las Palmeras','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2463','store_country'=>'ES','store_name'=>'Mirador de Jinamar','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2464','store_country'=>'ES','store_name'=>'Bahía Sur','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'Intermediate + RB SIS'],
            ['id'=>'2465','store_country'=>'ES','store_name'=>'Luz Shopping','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'2466','store_country'=>'ES','store_name'=>'Rambla de Cataluña','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS '],
            ['id'=>'2470','store_country'=>'ES','store_name'=>'La Maquinista','store_area'=>'Cataluña','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'2472','store_country'=>'ES','store_name'=>'Mataró','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate'],
            ['id'=>'2474','store_country'=>'ES','store_name'=>'La Rinconada','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate + 4.0 + RB SIS + Promo Table'],
            ['id'=>'2476','store_country'=>'ES','store_name'=>'Plaza Mayor','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS '],
            ['id'=>'2477','store_country'=>'ES','store_name'=>'Diagonal Mar ','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2478','store_country'=>'ES','store_name'=>'Las Rozas','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate'],
            ['id'=>'2479','store_country'=>'PT','store_name'=>'Factory Bonaire ','store_area'=>'Levante','store_segment'=>'Outlet','store_concept'=>'Intermediate + RB SIS + Promo Table'],
            ['id'=>'2481','store_country'=>'ES','store_name'=>'Artea','store_area'=>'Norte','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'2482','store_country'=>'ES','store_name'=>'La Morea','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'Intermediate'],
            ['id'=>'2485','store_country'=>'ES','store_name'=>'Licenciado Pozas ','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'6000 + RB SIS'],
            ['id'=>'2489','store_country'=>'ES','store_name'=>'Parque Principado','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2492','store_country'=>'ES','store_name'=>'Mirador ','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0 '],
            ['id'=>'2493','store_country'=>'ES','store_name'=>'Fuencarral ','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS'],
            ['id'=>'2494','store_country'=>'ES','store_name'=>'Santa Cruz','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2495','store_country'=>'ES','store_name'=>'Dos Mares','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'2496','store_country'=>'ES','store_name'=>'Baricentro ','store_area'=>'Cataluña','store_segment'=>'Silver','store_concept'=>'Intermediate '],
            ['id'=>'2497','store_country'=>'ES','store_name'=>'Dos Hermanas','store_area'=>'Andalucía','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'2499','store_country'=>'ES','store_name'=>'Valle Real','store_area'=>'Norte','store_segment'=>'Silver','store_concept'=>'2.0 Open Air'],
            ['id'=>'2507','store_country'=>'PT','store_name'=>'Dolce Vita Tejo Loja ','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'Intermediate '],
            ['id'=>'2508','store_country'=>'PT','store_name'=>'Colombo','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo table'],
            ['id'=>'2509','store_country'=>'PT','store_name'=>'Almada Forum ','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2517','store_country'=>'PT','store_name'=>'Norte Shopping','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'2519','store_country'=>'PT','store_name'=>'Vasco Da Gama','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'2521','store_country'=>'PT','store_name'=>'Braga Parque ','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS'],
            ['id'=>'2532','store_country'=>'PT','store_name'=>'Cascais Shopping','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'2534','store_country'=>'PT','store_name'=>'Aeroporto Porto','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'SIS 6000'],
            ['id'=>'2536','store_country'=>'PT','store_name'=>'Armazéns Chiado','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'2539','store_country'=>'PT','store_name'=>'Campera Outlet ','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'2541','store_country'=>'PT','store_name'=>'Foz Plaza ','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'Intermediate'],
            ['id'=>'2545','store_country'=>'PT','store_name'=>'Forum Montijo','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'2.0 Open Air'],
            ['id'=>'2546','store_country'=>'PT','store_name'=>'Acores','store_area'=>'Portugal 2','store_segment'=>'Silver','store_concept'=>'2.0 Open Air'],
            ['id'=>'2547','store_country'=>'PT','store_name'=>'Outlet Freeport ','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS + Promo Table'],
            ['id'=>'2548','store_country'=>'PT','store_name'=>'Dolce Vita Douro','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'2549','store_country'=>'PT','store_name'=>'Vila Do Conde','store_area'=>'Portugal 1','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'2550','store_country'=>'PT','store_name'=>'Alma Shopping (Dolce Vita Coimbra)','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'2552','store_country'=>'PT','store_name'=>'Alameda (Dolce Vita Antas)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'2554','store_country'=>'PT','store_name'=>'Forum  Coimbra ','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS'],
            ['id'=>'2556','store_country'=>'PT','store_name'=>'Arrabida Shopping ','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'2574','store_country'=>'PT','store_name'=>'Via Catarina','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'Intermediate'],
            ['id'=>'2575','store_country'=>'PT','store_name'=>'Mar Shopping','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'Intermediate '],
            ['id'=>'2577','store_country'=>'PT','store_name'=>'Estacao Viana do Castelo ','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'2718','store_country'=>'ES','store_name'=>'Dehesa Vieja','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'2720','store_country'=>'PT','store_name'=>'Aeroporto Lisboa (LX)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS '],
            ['id'=>'2771','store_country'=>'ES','store_name'=>'ECI 3 de Mayo','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS'],
            ['id'=>'2772','store_country'=>'ES','store_name'=>'ECI Diagonal','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'2773','store_country'=>'ES','store_name'=>'ECI Mesa y Lopez','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS'],
            ['id'=>'2774','store_country'=>'ES','store_name'=>'ECI 7 Palmas','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'2784','store_country'=>'ES','store_name'=>'Sitges','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'6000 + RB SIS'],
            ['id'=>'2866','store_country'=>'ES','store_name'=>'Ricardo Soriano','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'2967','store_country'=>'ES','store_name'=>'Aeropuerto BCN T1 Airside','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 '],
            ['id'=>'2998','store_country'=>'ES','store_name'=>"L'illa",'store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'2999','store_country'=>'ES','store_name'=>'Maremagnum','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'3011','store_country'=>'ES','store_name'=>'Aeropuerto Alicante ','store_area'=>'Levante ','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'3012','store_country'=>'ES','store_name'=>'Aeropuerto Málaga Airside ','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo table'],
            ['id'=>'3060','store_country'=>'PT','store_name'=>'Dolce Vita Funchal','store_area'=>'Portugal 1','store_segment'=>'Silver','store_concept'=>'2.0 Open Air'],
            ['id'=>'3064','store_country'=>'ES','store_name'=>'Jaume III','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'3079','store_country'=>'ES','store_name'=>'Aeropuerto Fuerteventura ','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'2.0 '],
            ['id'=>'3093','store_country'=>'ES','store_name'=>'Aeropuerto Gran Canaria','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0 '],
            ['id'=>'3098','store_country'=>'ES','store_name'=>'Aeropuerto Ibiza ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 '],
            ['id'=>'3102','store_country'=>'ES','store_name'=>'Aeropuerto Lanzarote','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0 '],
            ['id'=>'3103','store_country'=>'ES','store_name'=>'Aeropuerto Málaga Landside','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'3117','store_country'=>'ES','store_name'=>'Aeropuerto Mahón Menorca ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + 6000'],
            ['id'=>'3135','store_country'=>'ES','store_name'=>'Siam Mall','store_area'=>'Canarias','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'3140','store_country'=>'ES','store_name'=>'San Sebastian','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'3141','store_country'=>'ES','store_name'=>'Aeropuerto Tenerife Norte ','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'6000'],
            ['id'=>'3142','store_country'=>'ES','store_name'=>'Aeropuerto Tenerife Sur ','store_area'=>'Canarias','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'3176','store_country'=>'PT','store_name'=>'8 Avenida','store_area'=>'Portugal 3','store_segment'=>'Silver','store_concept'=>'Intermediate '],
            ['id'=>'3177','store_country'=>'PT','store_name'=>'Amoreiras','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'3182','store_country'=>'PT','store_name'=>'Madeira Shopping','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'Intermediate '],
            ['id'=>'3235','store_country'=>'ES','store_name'=>'ECI Campo de las Naciones','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'3258','store_country'=>'ES','store_name'=>'Larios','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'3575','store_country'=>'ES','store_name'=>'Factory Outlet Viladecans','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'2.0 + RB SIS + Promo Table'],
            ['id'=>'3768','store_country'=>'ES','store_name'=>'Cordoba / Gondomar','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'3774','store_country'=>'ES','store_name'=>'Aeropuerto Palma de Mallorca Mod D','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 '],
            ['id'=>'3775','store_country'=>'ES','store_name'=>'Mallorca Fashion Outlet (Festival Park) ','store_area'=>'Baleares','store_segment'=>'Outlet','store_concept'=>'2.0'],
            ['id'=>'3778','store_country'=>'ES','store_name'=>'Bilbao Gran Vía','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'3907','store_country'=>'ES','store_name'=>'Las Rozas Village ','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'3908','store_country'=>'ES','store_name'=>'Gran Jonquera','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'2.0'],
            ['id'=>'3914','store_country'=>'ES','store_name'=>'Aeropuerto Madrid T4 LS','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'4193','store_country'=>'ES','store_name'=>'Aeropuerto Palma de Mallorca Mod A ','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS + Promo Table'],
            ['id'=>'4243','store_country'=>'ES','store_name'=>'Serrano','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'4290','store_country'=>'ES','store_name'=>'ECI Princesa','store_area'=>'Madrid','store_segment'=>'Gold ','store_concept'=>'SIS 6000'],
            ['id'=>'4298','store_country'=>'ES','store_name'=>'ECI Vigo','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000 + RB SIS'],
            ['id'=>'4477','store_country'=>'PT','store_name'=>'Rua Augusta','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS '],
            ['id'=>'4490','store_country'=>'ES','store_name'=>'Portaferrissa','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'5031','store_country'=>'ES','store_name'=>'Recogidas','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'5103','store_country'=>'ES','store_name'=>'Porto Pi','store_area'=>'Baleares','store_segment'=>'Gold','store_concept'=>'2.0 '],
            ['id'=>'5222','store_country'=>'PT','store_name'=>'Aeroporto Funchal','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'Intermediate '],
            ['id'=>'5272','store_country'=>'PT','store_name'=>'Leiria','store_area'=>'Portugal 2','store_segment'=>'Gold','store_concept'=>'2.0 Open Air'],
            ['id'=>'5329','store_country'=>'ES','store_name'=>'ECI Independencia ','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5364','store_country'=>'ES','store_name'=>'ECI Cornellá','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5370','store_country'=>'ES','store_name'=>'ECI Badajoz Centro','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5396','store_country'=>'ES','store_name'=>'Aero Girona ','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5466','store_country'=>'ES','store_name'=>'ECI Tarragona','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5527','store_country'=>'ES','store_name'=>'ECI Valladolid','store_area'=>'Madrid','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5553','store_country'=>'ES','store_name'=>'ECI Puerto Banús','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'SIS 6000 + RB SIS'],
            ['id'=>'5554','store_country'=>'ES','store_name'=>'ECI Bahía de Cádiz','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'5620','store_country'=>'ES','store_name'=>'Juan de Austria','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'5650','store_country'=>'ES','store_name'=>'Málaga- Calle Granada','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS '],
            ['id'=>'6541','store_country'=>'ES','store_name'=>'Portal del Angel (Flasghip)','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'Flagship + RB SIS'],
            ['id'=>'7035','store_country'=>'ES','store_name'=>'ECI Preciados','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'SIS 2.0'],
            ['id'=>'7037','store_country'=>'ES','store_name'=>'ECI Palma de Mallorca','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'7039','store_country'=>'ES','store_name'=>'ECI Arabial','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'SIS 6000'],
            ['id'=>'7044','store_country'=>'ES','store_name'=>'ECI Marineda','store_area'=>'Madrid ','store_segment'=>'Silver','store_concept'=>'SIS 6000'],
            ['id'=>'7065','store_country'=>'ES','store_name'=>'Aeropuerto Madrid T4 AS ','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'2.0 + 6000 +RB SIS'],
            ['id'=>'7068','store_country'=>'ES','store_name'=>'Calle Gambo','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'2.0'],
            ['id'=>'7069','store_country'=>'ES','store_name'=>'Las Arenas BCN ','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'7700','store_country'=>'PT','store_name'=>'C.C. Nova Arcada','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'8593','store_country'=>'ES','store_name'=>'Logroño','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'8596','store_country'=>'ES','store_name'=>'Jerez de la Frontera (Lancería)','store_area'=>'Andalucía','store_segment'=>'Silver','store_concept'=>'2.0'],
            ['id'=>'8597','store_country'=>'ES','store_name'=>'Columela ','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'2.0 + RB SIS'],
            ['id'=>'8603','store_country'=>'ES','store_name'=>'Pamplona','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0 + ZIGZAG (RB-OO)'],
            ['id'=>'8606','store_country'=>'ES','store_name'=>'Santander','store_area'=>'Norte','store_segment'=>'Gold','store_concept'=>'2.0'],
            ['id'=>'8608','store_country'=>'ES','store_name'=>'Mahón ','store_area'=>'Baleares','store_segment'=>'Gold','store_concept'=>'2.0 '],
            ['id'=>'8609','store_country'=>'ES','store_name'=>'Aeropuerto Palma de Mallorca Mod C','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'8777','store_country'=>'PT','store_name'=>'Aeroporto Faro (Loja)','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0'],
            ['id'=>'8778','store_country'=>'PT','store_name'=>'Aeroporto Faro Kiosko','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0 Special'],
            ['id'=>'8779','store_country'=>'PT','store_name'=>'Aeroporto Lisboa T2','store_area'=>'Portugal 2','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'8910','store_country'=>'ES','store_name'=>'Aeropuerto Madrid T2','store_area'=>'Madrid','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'8993','store_country'=>'ES','store_name'=>'Aeropuerto MAD T3','store_area'=>'Madrid ','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9060','store_country'=>'ES ','store_name'=>'Tetuan','store_area'=>'Andalucía','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'9081','store_country'=>'ES','store_name'=>'Barakaldo Fashion Outlet','store_area'=>'Norte','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'9082','store_country'=>'ES','store_name'=>'Coruña The Style Outlet','store_area'=>'Madrid','store_segment'=>'Outlet','store_concept'=>'Intermediate '],
            ['id'=>'9128','store_country'=>'ES','store_name'=>'Gandía','store_area'=>'Levante','store_segment'=>'Silver','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9137','store_country'=>'ES','store_name'=>'Murcia Gran Vía','store_area'=>'Levante','store_segment'=>'Gold','store_concept'=>'Intermediate + RB SIS + 4.0'],
            ['id'=>'9140','store_country'=>'PT','store_name'=>'Rua do Carmo ','store_area'=>'Portugal 1','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'9141','store_country'=>'ES','store_name'=>'Aeropuerto Bilbao','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9142','store_country'=>'ES','store_name'=>'Jaume II','store_area'=>'Baleares','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9159','store_country'=>'ES','store_name'=>'Plaza Sant Jaume','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'9160','store_country'=>'ES','store_name'=>'El Muelle','store_area'=>'Canarias','store_segment'=>'Silver','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'9166','store_country'=>'ES','store_name'=>'Aeropuerto Valencia','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9167','store_country'=>'ES','store_name'=>'Aeropuerto Santiago','store_area'=>'Norte','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS '],
            ['id'=>'9192','store_country'=>'ES','store_name'=>'Aeropuerto BCN T1 No Schengen','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9193','store_country'=>'PT','store_name'=>'Algarve Outlet Inter Ikea','store_area'=>'Portugal 2','store_segment'=>'Outlet','store_concept'=>'3.0 + ZIGZAG (RB-OO)'],
            ['id'=>'9194','store_country'=>'PT','store_name'=>'Povoa','store_area'=>'Portugal 1','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS '],
            ['id'=>'9195','store_country'=>'ES','store_name'=>'Algeciras','store_area'=>'Andalucía','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS '],
            ['id'=>'9206','store_country'=>'ES','store_name'=>'Denia','store_area'=>'Levante','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9276','store_country'=>'PT','store_name'=>'Strada Outlet','store_area'=>'Portugal 2','store_segment'=>'Outlet','store_concept'=>'SGH-NXT + RB SIS'],
            ['id'=>'9281','store_country'=>'ES','store_name'=>'Outlet alicante','store_area'=>'Levante','store_segment'=>'Outlet','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9328','store_country'=>'ES','store_name'=>'Puigcerdá','store_area'=>'Cataluña','store_segment'=>'Gold','store_concept'=>'3.0 + RB SIS '],
            ['id'=>'9331','store_country'=>'PT','store_name'=>'Oeiras','store_area'=>'Portugal','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'9347','store_country'=>'ES','store_name'=>'La Roca Village ','store_area'=>'Cataluña','store_segment'=>'Outlet','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'9348','store_country'=>'ES','store_name'=>'Aero BCN T1 Airside Schengen (exAristocrazy)','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'3.0 + RB SIS'],
            ['id'=>'9530','store_country'=>'ES','store_name'=>'Finestrelles','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
            ['id'=>'9999','store_country'=>'ES','store_name'=>'ECI Diagonal','store_area'=>'Cataluña','store_segment'=>'Platinum','store_concept'=>'4.0 + RB SIS'],
                    ]);
    }
}
